### ISSUE TITLE
Passing a server cert in .DER format

### ISSUE THREAD

**Issue by jviveiros** [tafia/hyper-proxy#1]
I was able to do this with reqwest ( though I wasn't able to tunnel) - I could use it for HTTP endpoints only using standard http not connect. Anyway, Is there something like verify in python requests or another way to pass the cert file using your hyper-proxy. Most of my proxies are built with reqwest but my forward/firewall-ish one uses auth and requires a cert.

Thanks for your help!

**Comment by tafia** [comment]
I think you can set your own [tls](https://docs.rs/hyper-proxy/0.4.0/hyper_proxy/struct.ProxyConnector.html#method.set_tls) which then can use your [own certificate](https://docs.rs/native-tls/0.1.4/native_tls/struct.TlsConnectorBuilder.html#method.add_root_certificate).

hyper-proxy just got merged in reqwest so if needed this is probably something that can be integrated to reqwest as well (the tls part).
