### ISSUE TITLE
webpki-roots support

### ISSUE THREAD

**Issue by QuietMisdreavus** [tafia/hyper-proxy#15]
I'm looking to integrate hyper-proxy into [`egg-mode`](https://github.com/egg-mode-rs/egg-mode) (see egg-mode-rs/egg-mode#101). However, i also recently had an issue reported where a user couldn't use the native certificate store as loaded by `rustls-native-certs` (see egg-mode-rs/egg-mode#92). I fixed this at the time by exposing a feature from `hyper-rustls` that made it use statically-linked certificates from the `webpki-roots` crate instead of `rustls-native-certs`. Would you be open to exposing a Cargo feature to switch between these certificate stores?

**Comment by tafia** [comment]
I'm definitely opened to it but I don't have much time to do it myself.

**Comment by QuietMisdreavus** [comment]
No worries! I'll try to work it in myself and post a PR.
