### ISSUE TITLE
Custom tls connectors

### ISSUE THREAD

**Issue by frenchtoastbeer** [tafia/hyper-proxy#6]
I'm doing something like the following, so that I can intentionally mitm tls connections from my program:

```
let tls = TlsConnector::builder()
      .danger_accept_invalid_hostnames(true)
      .danger_accept_invalid_certs(true)
      .build();
let mut http = HttpConnector::new(4);
http.enforce_http(false);
let proxy_uri = proxy_uri.parse().unwrap();
let proxy = Proxy::new(Intercept::All, proxy_uri);
let connector = HttpsConnector::from( (http, tls.unwrap()) );
Client::builder()
      .build::<_, hyper::Body>( ProxyConnector::from_proxy(connector, proxy).unwrap() )
```

and the tls certificate for the proxy is still being checked for validity.  An attempt to switch to '.from_proxy_unsecured(...)' on the ProxyConnector is also failing, in that connections to secured hosts are being downgraded to mere http connections vs port 443.

**Comment by frenchtoastbeer** [comment]
Upon further investigation, it doesn't seem that the example code works either.  Proxy via TLS works well, but the plaintext response in the example code isn't issuing a proper request to the proxy, it just looks like a normal http request, but still sent to the proxy...

```
GET /wiki/Proxy_server HTTP/1.1
host: en.wikipedia.org
```

According to the standard, it should be a full URI in the requested resource, wikipedia had the following example...

`GET http://en.wikipedia.org/wiki/Proxy_server HTTP/1.1`

What gives?

**Comment by tafia** [comment]
Hey! Thanks for opening the issue. I do not have a lot of time for the moment but I'll try to have a look.

**Comment by frenchtoastbeer** [comment]
Ok thanks - here's the dependencies I used for your test project (just copied it from another project I was working on.
```
hyper = "0.12"
hyper-tls = "0.3"
hyper-proxy = "0.5.0"
tokio = "0.1"
futures = "0.1"
http = "0.1"
structopt = "0.2.14"
native-tls = "0.2.2"
pbr = "1.0.1"
rand = "*"
urlencoding = "1.0.0"
```

**Comment by frenchtoastbeer** [comment]
So Reqwest is handling both the insertion of headers and marking the connector as proxied, your library doesn't.  In the latest version of hyper, you can no longer call .set_proxy(true) on the Request, so this *I think* has to be handled by your library, or at least when the parent project is using hyper > 0.12.

I haven't yet figured out how to trigger an absolute URI in hyper 0.12.
